#!/usr/bin/env bash
"""transfer file to your server"""

if [$# -lt 4]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
