#!/usr/bin/env bash
"""redirection"""
sudo apt update -y
sudo apt install nginx -y

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
     listen	 80 default_server;
     listen	 [::]:80 default_server;
     root	 /etc/nginx/html;
     index	 index.html index.htm;

     location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;
     }
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
